#!/usr/bin/env bash
# ASC-0205 CC2' — AIOS sh installer (initial draft, 2026-05-20).
#
# Goal: a clean-environment install path for the AIOS operator surface.
# AIOS = production package; uri = testbed. This script installs the body.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/cjw0076/myworld/main/scripts/install.sh | bash
# or
#   ./scripts/install.sh [--prefix DIR]
#
# Closing criteria for ASC-0205 CC2':
#   1. clean env runs this end-to-end without manual edits
#   2. `aios --version` works afterward and returns a commit sha
#   3. at least one operator subcommand (dispatch/memory/contract) works
#   4. install.sh execution proven in CI (any green run)

set -euo pipefail

# --- config -----------------------------------------------------------------

AIOS_REPO_URL="${AIOS_REPO_URL:-https://github.com/cjw0076/myworld.git}"
AIOS_PREFIX="${AIOS_PREFIX:-$HOME/.aios}"
AIOS_BIN_DIR="${AIOS_BIN_DIR:-$HOME/.local/bin}"
AIOS_BRANCH="${AIOS_BRANCH:-main}"
PYTHON_MIN="3.11"

# --- helpers ----------------------------------------------------------------

log()  { printf '\033[1;36m[aios-install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[aios-install:warn]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[aios-install:fail]\033[0m %s\n' "$*" >&2; exit 1; }

ver_ge() {
  # ver_ge "$got" "$want" -> success if got >= want (dotted versions)
  printf '%s\n%s\n' "$2" "$1" | sort -V -C
}

# --- precheck ---------------------------------------------------------------

precheck() {
  log "checking prerequisites"

  command -v git >/dev/null || fail "git not found (apt/brew install git)"
  command -v python3 >/dev/null || fail "python3 not found (need >= $PYTHON_MIN)"

  local py_ver
  py_ver="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
  if ! ver_ge "$py_ver" "$PYTHON_MIN"; then
    fail "python $py_ver < $PYTHON_MIN required"
  fi
  log "python $py_ver ok"

  mkdir -p "$AIOS_BIN_DIR"
}

# --- clone / update ---------------------------------------------------------

fetch_repo() {
  if [ -d "$AIOS_PREFIX/.git" ]; then
    log "updating existing checkout at $AIOS_PREFIX"
    git -C "$AIOS_PREFIX" fetch --depth=1 origin "$AIOS_BRANCH"
    git -C "$AIOS_PREFIX" reset --hard "origin/$AIOS_BRANCH"
  else
    log "cloning $AIOS_REPO_URL -> $AIOS_PREFIX"
    git clone --depth=1 --branch "$AIOS_BRANCH" "$AIOS_REPO_URL" "$AIOS_PREFIX"
  fi
}

# --- aios entrypoint --------------------------------------------------------

install_entrypoint() {
  local entry="$AIOS_BIN_DIR/aios"
  log "writing $entry"
  cat > "$entry" <<'EOF'
#!/usr/bin/env bash
# AIOS operator CLI entrypoint (generated by scripts/install.sh).
# Routes 'aios <subcommand>' to scripts/aios_*.py.
set -euo pipefail
AIOS_PREFIX="${AIOS_PREFIX:-$HOME/.aios}"
SUB="${1:-help}"
shift || true

case "$SUB" in
  --version|version)
    sha="$(git -C "$AIOS_PREFIX" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    echo "aios $sha (prefix=$AIOS_PREFIX)"
    ;;
  dispatch)
    exec python3 "$AIOS_PREFIX/scripts/aios_dispatch.py" "$@"
    ;;
  memory)
    cd "$AIOS_PREFIX/memoryOS" && exec python3 -m memoryos --root . "$@"
    ;;
  contract|contracts)
    exec ls -1 "$AIOS_PREFIX/docs/contracts/"
    ;;
  readiness)
    exec python3 "$AIOS_PREFIX/scripts/aios_readiness.py" "$@"
    ;;
  primitives)
    exec python3 "$AIOS_PREFIX/scripts/aios_primitives.py" "$@"
    ;;
  help|*)
    cat <<EOH
aios — operator CLI entrypoint
usage: aios <command> [...args]
  --version          print commit sha
  dispatch ...       AIOS contract dispatch
  memory ...         memoryOS CLI (drafts, audit, ...)
  contract           list contracts
  readiness ...      L0..L6 readiness check
  primitives ...     web/monitor/task/ask/tools
EOH
    ;;
esac
EOF
  chmod +x "$entry"
}

# --- post-install verify ----------------------------------------------------

verify() {
  log "verifying"
  if ! "$AIOS_BIN_DIR/aios" --version; then
    fail "aios --version failed"
  fi
  log "ok — make sure $AIOS_BIN_DIR is on your PATH"
}

# --- main -------------------------------------------------------------------

main() {
  while [ $# -gt 0 ]; do
    case "$1" in
      --prefix) AIOS_PREFIX="$2"; shift 2;;
      --bin-dir) AIOS_BIN_DIR="$2"; shift 2;;
      --branch) AIOS_BRANCH="$2"; shift 2;;
      --repo) AIOS_REPO_URL="$2"; shift 2;;
      -h|--help)
        cat <<EOH
install.sh — AIOS sh installer
options:
  --prefix DIR    install root (default: \$HOME/.aios)
  --bin-dir DIR   where to place the 'aios' entry (default: \$HOME/.local/bin)
  --branch NAME   git branch (default: main)
  --repo URL      git url (default: $AIOS_REPO_URL)
env: AIOS_PREFIX / AIOS_BIN_DIR / AIOS_BRANCH / AIOS_REPO_URL
EOH
        exit 0;;
      *) fail "unknown arg: $1";;
    esac
  done

  precheck
  fetch_repo
  install_entrypoint
  verify
}

main "$@"
